export const DAILY_SPARKS = [
  "Logic is the beginning of all wisdom.",
  "First, solve the problem. Then, write code.",
  "Simple is better than complex.",
  "Precision is the soul of engineering.",
  "Signals fade, but logic remains eternal.",
  "Build for the future you want to see.",
  "Code is poetry written in pure logic.",
  "Hardware is where magic becomes physical.",
  "Optimize for clarity, not just for speed.",
  "Small steps lead to massive systems.",
  "Consistency beats intensity every single time.",
  "A good system is a silent system.",
  "Design is not just how it looks.",
  "Simplify until only the essence remains.",
  "Debugging is being the detective in code.",
  "Measure twice, cut once, then code once.",
  "The best way to predict is to invent.",
  "Complexity is the enemy of reliability.",
  "Great things are built one bit at a time.",
  "Every breakthrough starts with a curious mind.",
  "Think in systems, act in components.",
  "Elegance is the ultimate form of sophistication.",
  "Stay hungry for knowledge, stay humble.",
  "Your only limit is your own imagination.",
  "Algorithms are thoughts turned into reality.",
  "Master the fundamentals, then break the rules.",
  "Focus on the process, not the result.",
  "Quality is not an act, it is a habit.",
  "Write code that your future self loves.",
  "Engineering is the art of organized thinking.",
  "Innovation happens at the edges of knowledge.",
  "Don't just build, understand why it works.",
  "Entropy increases; keep your systems clean.",
  "Signals require a clear path to follow.",
  "The best hardware is invisible to users.",
  "Read the documentation, then write the future.",
  "Logic doesn't care about your feelings.",
  "Structure your thoughts before you build.",
  "Great architecture survives the test of time.",
  "Prototypes are for learning, products are for users.",
  "Solve for the user, not the ego.",
  "Automate the boring, innovate the exciting.",
  "A bug is an opportunity to learn.",
  "Version control is your best friend.",
  "Think deeply, execute swiftly.",
  "Data is the new currency of engineering.",
  "Neural networks learn; so should you.",
  "The future is built on silicon and soul.",
  "Stay curious about how things work.",
  "Clean code is a love letter to teammates.",
  "Dream in binary, live in high resolution.",
  "Success is a series of successful iterations.",
  "Logic is the foundation of all magic.",
  "Make it work, make it right, then fast.",
  "Hardware eventually fails; software is forever.",
  "The world runs on ECE fundamentals.",
  "Silicon remembers what logic commands.",
  "Every circuit tells a unique story.",
  "Bandwidth is limited; use your energy wisely.",
  "Frequency matters in signals and in life.",
  "Resist noise, amplify the truth.",
  "Feedback loops are the key to growth.",
  "The best designs are often the simplest.",
  "Create tools that empower other people.",
  "Knowledge is the ultimate competitive advantage.",
  "Learn to listen to what data says.",
  "The grid is your canvas; build something.",
  "Architecture is the art of trade-offs.",
  "Stay grounded, but keep your head high.",
  "Amplify your strengths, filter the distractions.",
  "Every day is a chance to refactor.",
  "Build bridges, not just systems.",
  "Logic is the shortest path to truth.",
  "Your mind is the most powerful processor.",
  "Efficiency is doing more with less.",
  "The best algorithm is a simple one.",
  "Innovate today, legacy code tomorrow.",
  "Build it well or don't build it.",
  "Engineering is problem solving with constraints.",
  "The signal must be stronger than noise.",
  "Understand the hardware to master the software.",
  "Life is an iterative process of learning.",
  "Design for the human, build for machine.",
  "Logic is a universal language.",
  "Stay synchronized with your goals.",
  "The future is a system you design.",
  "Great engineering requires both heart and head.",
  "Every line of code should have purpose.",
  "Simplicity is the ultimate technical achievement.",
  "Master the basics to achieve the complex.",
  "Logic and creativity are two sides of one.",
  "Build systems that can handle the unexpected.",
  "Innovation is just a series of experiments.",
  "Keep your logic sharp and code clean.",
  "Great engineers never stop being students.",
  "The world needs your unique perspective.",
  "Signal processing is the art of hearing.",
  "Digital thoughts, analog feelings.",
  "Transform inputs into meaningful outputs.",
  "Systems work best when parts communicate.",
  "Design for reliability, build for scale.",
  "Architecture starts with a single line.",
  "Logic is the rhythm of the universe.",
  "Code for tomorrow, build for today.",
  "The best solution is the one you find.",
  "Stay focused on the core problem.",
  "Every system has a point of failure.",
  "Design to prevent failure, build to recover.",
  "Intelligence is the ability to adapt.",
  "Stay hungry, stay curious, stay building.",
  "Logic is the key to every door.",
  "Build something you are proud of today.",
  "Your efforts today power your future.",
  "Engineering is turning dreams into reality.",
  "Great systems are built with empathy.",
  "Listen to the feedback, ignore the noise.",
  "Precision beats power every single time.",
  "Logic is the compass of the mind.",
  "Build it simple, build it strong.",
  "The best code is no code at all.",
  "Understand the stack from bottom to top.",
  "Silicon dreams become real world solutions.",
  "Design systems that respect the user.",
  "Knowledge grows when it is shared.",
  "Logic is the bridge to the future.",
  "Build with purpose, live with passion.",
  "Every problem has a logical solution.",
  "Iteration is the heartbeat of progress.",
  "Stay analytical, remain creative.",
  "Engineering is a service to humanity.",
  "The best designs require no manual.",
  "Focus on the signal, ignore the rest.",
  "Architecture is the language of systems.",
  "Logic is the backbone of technology.",
  "Build for impact, not just for show.",
  "Simplicity is the soul of efficiency.",
  "Master the tools, then invent new ones.",
  "The future is coded in our actions.",
  "Stay grounded in facts and logic.",
  "Design for clarity, code for performance.",
  "Great systems are intuitive and robust.",
  "Innovation requires the courage to fail.",
  "Logic is the light in the dark.",
  "Build things that last beyond a lifetime.",
  "Every success is built on failed attempts.",
  "Understand the physics to master the electronics.",
  "Logic is the path to true innovation.",
  "Stay consistent, stay persistent, stay building.",
  "Design systems that are easy to maintain.",
  "The best engineers are great listeners.",
  "Logic is the ultimate problem solver.",
  "Build a better world, one bit daily.",
  "Your potential is a powerful energy source.",
  "Engineering is the bridge to tomorrow.",
  "Stay sharp, stay logical, stay curious.",
  "Design for accessibility, build for everyone.",
  "Logic is the music of reason.",
  "Build systems that empower human potential.",
  "Every breakthrough was once an impossibility.",
  "Focus on the signal in the static.",
  "Architecture defines the soul of a system.",
  "Logic is the most powerful tool.",
  "Build with integrity, live with purpose.",
  "The future is a product of design.",
  "Stay inquisitive about the world around.",
  "Design with intent, build with care.",
  "Logic is the foundation of progress.",
  "Build things that solve real problems.",
  "Every line of code is a choice.",
  "Engineering is the pursuit of perfection.",
  "Stay humble in success, resilient in failure.",
  "Design systems that are beautiful and functional.",
  "Logic is the heartbeat of the machine.",
  "Build for the long term, not short.",
  "The best engineers value simplicity most.",
  "Logic is the key to clarity.",
  "Build with the user in mind always.",
  "Every challenge is a design opportunity.",
  "Stay focused on the user experience.",
  "Design for resilience, build for longevity.",
  "Logic is the guide to innovation.",
  "Build something that matters to someone.",
  "Your work is a reflection of you.",
  "Engineering is the art of the possible.",
  "Stay dedicated to your craft daily.",
  "Design for simplicity, build for robustness.",
  "Logic is the language of the future.",
  "Build with heart, engineer with mind.",
  "Every project is a learning journey.",
  "Stay passionate about solving problems.",
  "Design for the future, learn from past.",
  "Logic is the strength of a system.",
  "Build systems that can evolve gracefully.",
  "Innovation is the result of persistent effort.",
  "Logic is the core of all tech.",
  "Build for excellence, not just for completion.",
  "Your curiosity is your greatest asset.",
  "Engineering is the logic of creation.",
  "Stay committed to your engineering goals.",
  "Design for the user, engineer for machine.",
  "Logic is the light of progress.",
  "Build with precision, live with purpose.",
  "Every system starts with a single thought.",
  "Stay analytical, remain bold and brave.",
  "Design systems that make life easier.",
  "Logic is the path to excellence.",
  "Build for impact, engineer for reliability.",
  "Innovation is a journey of discovery.",
  "Logic is the key to every system.",
  "Build something useful for the world.",
  "Your efforts today shape the world tomorrow.",
  "Engineering is the art of logic.",
  "Stay curious, stay building, stay hungry.",
  "Design for clarity, build for performance.",
  "Logic is the foundation of all tech.",
  "Build for the future, starting today.",
  "Every line counts, every bit matters.",
  "Stay focused on your engineering vision.",
  "Design with empathy, build with logic.",
  "Logic is the soul of innovation.",
  "Build for everyone, engineer for quality.",
  "Innovation is born from curious minds.",
  "Logic is the heart of engineering.",
  "Build with purpose, design for people.",
  "Your journey is a series of builds.",
  "Engineering is the pursuit of logic.",
  "Stay logical, stay creative, stay bold.",
  "Design for the user, build for future.",
  "Logic is the bridge to success.",
  "Build things that improve the world.",
  "Every success starts with a single build.",
  "Stay dedicated to your technical craft.",
  "Design with logic, build with passion.",
  "Logic is the key to all systems.",
  "Build with heart, design with mind.",
  "Your curiosity powers your engineering path.",
  "Engineering is the art of the logic.",
  "Stay building, stay learning, stay great.",
  "Design for the future, build for today.",
  "Logic is the soul of all technology.",
  "Build with excellence, engineer for people.",
  "Every line of code should count.",
  "Stay focused on the core solution.",
  "Design with intent, build with precision.",
  "Logic is the foundation of your builds.",
  "Build something meaningful every single day.",
  "Your work shapes the technical world.",
  "Engineering is the logic of the future.",
  "Stay sharp, stay building, stay curious.",
  "Design for impact, build for quality.",
  "Logic is the key to every breakthrough.",
  "Build with integrity, engineer for users.",
  "Innovation is the result of curiosity.",
  "Logic is the heart of all innovation.",
  "Build for the future, design for today.",
  "Every bit matters, every line counts.",
  "Stay committed to your engineering path.",
  "Design with logic, build for people.",
  "Logic is the soul of your work.",
  "Build for everyone, engineer for excellence.",
  "Innovation starts with a curious question.",
  "Logic is the key to all logic.",
  "Build with purpose, design for impact.",
  "Your efforts today power the future.",
  "Engineering is the pursuit of the truth.",
  "Stay logical, stay bold, stay building.",
  "Design for the future, build for people.",
  "Logic is the bridge to tomorrow.",
  "Build things that make a difference.",
  "Every build is a step forward.",
  "Stay curious about every single system.",
  "Design with logic, build with heart.",
  "Logic is the soul of all builds.",
  "Build with heart, design for future.",
  "Your journey is defined by your builds.",
  "Engineering is the art of the machine.",
  "Stay hungry for knowledge and logic.",
  "Design for impact, build for everyone.",
  "Logic is the key to every project.",
  "Build something great every single day.",
  "Your work is your engineering legacy.",
  "Engineering is the logic of innovation.",
  "Stay sharp, stay logical, stay building.",
  "Design for quality, build for users.",
  "Logic is the heart of all tech.",
  "Build with integrity, design for impact.",
  "Innovation is a result of logic.",
  "Logic is the foundation of all innovation.",
  "Build for today, design for tomorrow.",
  "Every success is a series of builds.",
  "Stay focused on your technical vision.",
  "Design with logic, build for success.",
  "Logic is the soul of your builds.",
  "Build with heart, engineer for future.",
  "Your efforts today are your future.",
  "Engineering is the pursuit of excellence.",
  "Stay bold, stay logical, stay building.",
  "Design for people, build with logic.",
  "Logic is the bridge to all success.",
  "Build things that matter for everyone.",
  "Every line of code is progress.",
  "Stay inquisitive about all technical things.",
  "Design with logic, build with soul.",
  "Logic is the soul of every machine.",
  "Build with heart, design for today.",
  "Your work is your engineering story.",
  "Engineering is the logic of the people.",
  "Stay hungry, stay sharp, stay building.",
  "Design for users, build for impact.",
  "Logic is the key to all creation.",
  "Build something beautiful and logical today.",
  "Your work is your technical fingerprint.",
  "Engineering is the logic of your world.",
  "Stay creative, stay analytical, stay building.",
  "Design for everyone, build for future.",
  "Logic is the soul of every system.",
  "Build with purpose, design with heart.",
  "Every project is a building block.",
  "Stay dedicated to your technical goals.",
  "Design with intent, build with excellence.",
  "Logic is the heart of every build.",
  "Build something you love every day.",
  "The future is built on logic today."
];

export const getSparkForDate = (date) => {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  // Use modulo to wrap around if array is shorter than 366
  return DAILY_SPARKS[dayOfYear % DAILY_SPARKS.length];
};